### ISSUE TITLE
--no-ip-route is broken

### ISSUE THREAD

**Issue by petergjoel** [DEIS-Tools/AalWiNes#57]
check
`<$mpls ip> .* < mpls+ $mpls ip> 0 DUAL`
on the nn-example using `--no-ip-route -e 1 --routing ./nn-routing.xml --topology ./nn-topology.xml -q ./query.q -r 3  -t`.

There is an IP-hop mid trace which should be disabled by the `--no-ip-route` flag.

**Comment by petergjoel** [comment]
@MortenSchou is this still an issue or has this been fixed?

**Comment by MortenSchou** [comment]
@petergjoel I was not able to recreate it. But I don't know if that is just random or if it was actually fixed.
Anyway, I am working on the new PDA construction (and CEGAR), and I hope to get the semantics described properly in the model before trying to implement a quick-fix.

**Comment by MortenSchou** [comment]
Fixed by #92, which changes the model of the header incl. removing the need for `--no-ip-route` flag.
