### ISSUE TITLE
pre error formatting error

### ISSUE THREAD

**Issue by djm97** [DEIS-Tools/AalWiNes#79]
For some queries I get {"pre":"error"}  ,which results into a formatting error, because of the missing "," between {"pre":"error"} and the trace description.
I get this error just for dual mode, so when I use the same query with over or under. It doesn't appear.
The main problem with the formatting error is that it makes the json file unreadable

"Q124" : {
      "query": "<.>  [.#Alice_Springs,Alice_Springs#.] .* [.#Melbourne1,Melbourne1#.]  <.> 2 DUAL",
      "result":true,
      "engine": "Post*", 
      "mode": "UNDER", 
      "reduction":[110101, 110101],
      "trace":[
{"pre":"error"}          {"from_router":"NULL","from_interface":"i61","to_router":"Alice_Springs","to_interface":"eg0","stack":["ip6"]},
         {"ingoing":"eg0","pre":"ip","rule":{"weight":2, "via":"in0", "ops":[{"push":"s1567"}, {"push":"1751"}, {"push":"1753"}]}},
         {"from_router":"Alice_Springs","from_interface":"in0","to_router":"Adelaide2","to_interface":"in3","stack":["1753","1751","s1567","ip6"]},
         {"ingoing":"in3","pre":"1753","rule":{"weight":0, "via":"in1", "ops":[{"swap":"1752"}]}},
         {"from_router":"Adelaide2","from_interface":"in1","to_router":"Adelaide1","to_interface":"in2","stack":["1752","1751","s1567","ip6"]},
         {"ingoing":"in2","pre":"1752","rule":{"weight":0, "via":"in1", "ops":["pop"]}},
         {"from_router":"Adelaide1","from_interface":"in1","to_router":"Darwin","to_interface":"in0","stack":["1751","s1567","ip6"]},
         {"ingoing":"in0","pre":"1751","rule":{"weight":0, "via":"in0", "ops":[{"swap":"1750"}]}},
         {"from_router":"Darwin","from_interface":"in0","to_router":"Adelaide1","to_interface":"in1","stack":["1750","s1567","ip6"]},
         {"ingoing":"in1","pre":"1750","rule":{"weight":0, "via":"in2", "ops":["pop"]}},
         {"from_router":"Adelaide1","from_interface":"in2","to_router":"Adelaide2","to_interface":"in1","stack":["s1567","ip6"]},
         {"ingoing":"in1","pre":"s1567","rule":{"weight":0, "via":"in1", "ops":[{"swap":"s1568"}]}},
         {"from_router":"Adelaide2","from_interface":"in1","to_router":"Adelaide1","to_interface":"in2","stack":["s1568","ip6"]},
         {"ingoing":"in2","pre":"s1568","rule":{"weight":0, "via":"in3", "ops":[{"swap":"s1569"}]}},
         {"from_router":"Adelaide1","from_interface":"in3","to_router":"Melbourne1","to_interface":"in2","stack":["s1569","ip6"]},
         {"ingoing":"in2","pre":"s1569","rule":{"weight":0, "via":"eg0", "ops":["pop"]}},
         {"from_router":"Melbourne1","from_interface":"eg0","to_router":"NULL","to_interface":"i51","stack":["ip6"]}
      ],
      "compilation-time":0.201861,
      "reduction-time":0.0005006,
      "verification-time":0.0883355

**Comment by petergjoel** [comment]
Could you attach a model and query-file so we can reproduce the issue?

**Comment by djm97** [comment]
[queries.txt](https://github.com/DEIS-Tools/AalWiNes/files/4967508/queries.txt)


[routing.txt](https://github.com/DEIS-Tools/AalWiNes/files/4967522/routing.txt)


[topo.txt](https://github.com/DEIS-Tools/AalWiNes/files/4967523/topo.txt)

**Comment by djm97** [comment]
For the exact same query for over or under mode this error doesn't occur.
Also just for max_link_failure = 1.
I tried 0 and 2 and there the error didn't occurred as well.

**Comment by petergjoel** [comment]
Which version is this bug related to?

I am unable to reproduce with the neither the journal release (V0.92.J) or the current master.

**Comment by djm97** [comment]
I use the current master. I forgot to mention that I use engine 1 and of course the -t option.
For engine 2 or 3 unweighted pre error doesn't occur
