### ISSUE TITLE
Negative compilation and verification times

### ISSUE THREAD

**Issue by djm97** [DEIS-Tools/AalWiNes#80]
Sometimes I get negative compilation or verification  times.
I don't think it has something to do with the query or weights in specific, because I trie the same Configuration a few times and it was never the case, that negative compilation or verification times occurred more than once.

**Comment by petergjoel** [comment]
Can you past and example of the erroneous output?

**Comment by MortenSchou** [comment]
@djm97, we have not experienced this bug before. Can you provide some more information about it? Otherwise, there is not much we can do. 😃

**Comment by MortenSchou** [comment]
Closing issue due to lack of clarification.
