### ISSUE TITLE
Add --version and --license

### ISSUE THREAD

**Issue by petergjoel** [DEIS-Tools/AalWiNes#89]
Both these standard options are missing - and --version is quite useful in practice (in particular if it is paired with a git-hash).

**Comment by MortenSchou** [comment]
--version with git-hash is implemented with this commit: https://github.com/MortenSchou/AalWiNes/commit/2f1e02384d076d5f63fa3c3c1dd03d8f523f2625

For --license, do you have an example of the usual output? Is it just the text of the GPL license, or do we need to add some copyright and names too?

**Comment by petergjoel** [comment]
Yes, `--license` should produce the GPL notice + the authors (you, me, Dan, Bernhard, and Yrke) 

(see `ls --version` for instance)
